#!/home/kingb/aim/venv/bin/python3
import os
import time
import json
import subprocess
from datetime import datetime

# --- CONFIGURATION (Load from core/CONFIG.json) ---
def find_aim_root(start_dir):
    current = os.path.abspath(start_dir)
    while current != '/':
        config_path = os.path.join(current, "core/CONFIG.json")
        if os.path.exists(config_path):
            return current
        current = os.path.dirname(current)
    return "/home/kingb/aim"

AIM_ROOT = find_aim_root(os.getcwd())
CONFIG_PATH = os.path.join(AIM_ROOT, "core/CONFIG.json")

with open(CONFIG_PATH, 'r') as f:
    CONFIG = json.load(f)

HEARTBEAT_FILE = os.path.join(AIM_ROOT, "core/HEARTBEAT.md")
# TEST INTERVAL: 5 minutes (300s). PRODUCTION: 3-4 hours.
INTERVAL = 300 

def get_external_changes():
    """Checks if any files have changed in the git repo."""
    try:
        status = subprocess.check_output(["git", "status", "--short"], 
                                         cwd=AIM_ROOT, text=True).strip()
        if not status:
            return "No external changes detected."
        return f"External changes detected since last heartbeat:\n```text\n{status}\n```"
    except Exception as e:
        return f"Error checking git status: {e}"

def run_heartbeat():
    while True:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        changes = get_external_changes()
        
        heartbeat_content = f"# A.I.M. Heartbeat Pulse: {timestamp}\n\n"
        heartbeat_content += f"## 🛠️ Watchman Report\n{changes}\n\n"
        heartbeat_content += "---\n*Auto-generated by Pillar A Daemon*"
        
        with open(HEARTBEAT_FILE, "w") as f:
            f.write(heartbeat_content)
            
        time.sleep(INTERVAL)

if __name__ == "__main__":
    # Ensure only one daemon is running
    # (Simple pid-file logic could go here, but starting via SessionStart is usually enough)
    run_heartbeat()
