#!/usr/bin/env python3
import os
import json
import glob
import sys
import shutil
from datetime import datetime
from reasoning_utils import generate_reasoning, AIM_ROOT

# --- CONFIGURATION ---
CONFIG_PATH = os.path.join(AIM_ROOT, "core/CONFIG.json")
with open(CONFIG_PATH, 'r') as f:
    CONFIG = json.load(f)

DAILY_LOG_DIR = CONFIG['paths'].get('memory_dir')

def chancellor_audit(target_date=None):
    """
    Tier 2: Consolidates the Librarian's Daily Log into a Daily Milestone Report.
    """
    date_str = target_date or datetime.now().strftime("%Y-%m-%d")
    print(f"--- A.I.M. CHANCELLOR AUDIT: {date_str} ---")
    
    # 1. Gather the Daily Log generated by the Librarian
    log_path = os.path.join(DAILY_LOG_DIR, f"{date_str}.md")
    
    if not os.path.exists(log_path):
        print(f"  [SKIP] No Librarian daily log found for {date_str}.")
        return

    print(f"  -> Reading daily log for synthesis...")
    
    with open(log_path, 'r') as f:
        log_content = f.read()

    # 2. Scholastic Reasoning (Chancellor Tier)
    prompt = f"""
You are the A.I.M. Chancellor (Tier 2 Specialist). Your goal is to synthesize the Librarian's daily log into a single, surgical 'Daily Milestone Report'.

MANDATE:
1. FOCUS: Only capture logic shifts, finished features, and major technical hurdles.
2. DISCARD: Remove granular task-level chatter. 
3. VERIFIABLE: Ensure all file paths and symbols are preserved.
4. TONE: Dry, technical, and high-fidelity.

LIBRARIAN DAILY LOG FOR {date_str}:
{log_content}

Output format:
## Daily Milestone Report: {date_str}
### 🚀 Key Technical Achievements
(Surgical bullets)

### 🏗️ Architectural Shifts
(Changes to logic or structure)

### 📍 Project Edge
(Exactly where the project stands at the end of the day)
"""

    system_instr = "You are a high-level technical chancellor. Consolidate granular history into strategic milestones."

    try:
        # Route to Chancellor tier reasoning
        report = generate_reasoning(prompt, system_instruction=system_instr, brain_type="chancellor")
        
        # Save the Daily Report
        report_path = os.path.join(DAILY_LOG_DIR, f"DAILY_REPORT_{date_str}.md")
        with open(report_path, 'w') as f:
            f.write(report)
        
        print(f"  [SUCCESS] Daily Report generated: {os.path.basename(report_path)}")
        
        # 3. ARCHIVE THE USED LOG
        # We rename the daily log to denote it has been synthesized
        archive_dir = os.path.join(DAILY_LOG_DIR, "archive", "daily_logs")
        os.makedirs(archive_dir, exist_ok=True)
        try:
            shutil.move(log_path, os.path.join(archive_dir, os.path.basename(log_path)))
            print(f"  [SUCCESS] Archived raw daily log.")
        except Exception as move_e:
            print(f"  [WARNING] Could not move raw log to archive: {move_e}")
            
    except Exception as e:
        print(f"  [ERROR] Chancellor reasoning failed: {e}")

if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else None
    chancellor_audit(target)
